import os
import sys
import time
from pathlib import Path
from typing import Dict, Any, Optional, Callable, List
import config
from core.llm_engine import LLMEngine
from core.tts_engine import TTSEngine
from core.image_engine import ImageEngine
from core.video_engine import VideoEngine
from core.publisher import MetaPublisher
from core.tag_engine import TagOptimizer


class ReelPipeline:
    def __init__(
        self,
        voice: str = config.DEFAULT_VOICE,
        gemini_key: Optional[str] = None,
        groq_key: Optional[str] = None
    ):
        self.voice = voice
        self.llm = LLMEngine(gemini_api_key=gemini_key, groq_api_key=groq_key)
        self.tts = TTSEngine(default_voice=voice)
        self.image_gen = ImageEngine(width=config.VIDEO_WIDTH, height=config.VIDEO_HEIGHT)
        self.video_gen = VideoEngine(width=config.VIDEO_WIDTH, height=config.VIDEO_HEIGHT, fps=config.FPS)
        self.publisher = MetaPublisher()

    def generate_full_reel(
        self,
        prompt: str,
        niche: str = "General",
        voice: Optional[str] = None,
        bg_music_path: Optional[Path] = None,
        custom_tags: Optional[str] = None,
        custom_mentions: Optional[str] = None,
        audio_name: str = "Original Audio • ND Studio",
        share_to_feed: bool = True,
        allow_remixing: bool = True,
        auto_publish: bool = False,
        progress_callback: Optional[Callable[[str, float], None]] = None
    ) -> Dict[str, Any]:
        """
        Executes the full automated reel creation lifecycle with algorithmic optimization.
        """
        start_time = time.time()
        job_id = f"reel_{int(start_time)}"
        job_dir = config.OUTPUT_DIR / job_id
        job_dir.mkdir(parents=True, exist_ok=True)

        selected_voice = voice or self.voice

        def notify(msg: str, pct: float):
            print(f"[{int(pct*100)}%] {msg}")
            if progress_callback:
                progress_callback(msg, pct)

        # 1. Script Generation
        notify("Generating viral script and scene visual prompts...", 0.1)
        script_data = self.llm.generate_script(prompt, niche)
        title = script_data.get("title", "Daily Discovery")
        scenes = script_data.get("scenes", [])
        base_caption = script_data.get("caption", "")

        if not scenes:
            raise ValueError("No scenes generated by LLM engine.")

        # 2. Tag Optimization & Caption Formatting
        tags_info = TagOptimizer.generate_tags(
            prompt=prompt,
            niche=niche,
            custom_tags=custom_tags,
            custom_mentions=custom_mentions
        )
        full_caption = TagOptimizer.format_optimized_caption(base_caption, tags_info)

        processed_scenes = []
        total_scenes = len(scenes)

        # 3. Audio & Visuals per Scene
        for i, scene in enumerate(scenes):
            scene_num = i + 1
            narration = scene.get("narration", "")
            vis_prompt = scene.get("visual_prompt", "")

            notify(f"Generating scene {scene_num}/{total_scenes}: Neural voiceover...", 0.2 + (0.2 * (i / total_scenes)))
            audio_file = job_dir / f"scene_{scene_num}_audio.mp3"
            self.tts.generate_voiceover(narration, audio_file, voice=selected_voice)

            notify(f"Generating scene {scene_num}/{total_scenes}: 9:16 AI Visual...", 0.3 + (0.2 * (i / total_scenes)))
            img_file = job_dir / f"scene_{scene_num}_image.jpg"
            self.image_gen.generate_image(vis_prompt, img_file)

            processed_scenes.append({
                "scene_id": scene_num,
                "narration": narration,
                "image_path": img_file,
                "audio_path": audio_file
            })

        # 4. Video Assembly, Ken Burns Motion, and Audio Ducking
        notify("Rendering animated 9:16 video with dynamic subtitles & background music...", 0.7)
        final_video_path = job_dir / f"{job_id}_final.mp4"
        self.video_gen.assemble_reel(
            scenes_data=processed_scenes,
            output_path=final_video_path,
            bg_music_path=bg_music_path
        )

        # 5. Extract High-CTR Cover Thumbnail Frame
        cover_path = self.publisher.extract_cover_thumbnail(final_video_path)

        # 6. Save to Queue / Auto-Publish
        notify("Saving reel to library and publishing queue...", 0.9)
        self.publisher.save_to_publish_queue(
            video_path=final_video_path,
            title=title,
            caption=full_caption,
            hashtags=tags_info["tags"],
            metadata={
                "cover_path": str(cover_path),
                "audio_name": audio_name,
                "share_to_feed": share_to_feed,
                "allow_remixing": allow_remixing
            }
        )

        publish_result = None
        if auto_publish:
            notify("Triggering Meta Auto-Publishing...", 0.95)
            if self.publisher.is_configured()["facebook"]:
                publish_result = self.publisher.publish_facebook_reel(
                    video_path=final_video_path,
                    caption=full_caption,
                    title=title,
                    allow_remixing=allow_remixing
                )

        notify("Reel generated successfully!", 1.0)

        elapsed = time.time() - start_time
        return {
            "job_id": job_id,
            "title": title,
            "video_path": str(final_video_path),
            "cover_path": str(cover_path),
            "script_data": script_data,
            "caption": full_caption,
            "hashtags": tags_info["tags"],
            "elapsed_seconds": round(elapsed, 1),
            "published": publish_result
        }
