import os
import sys
import time
from pathlib import Path
from typing import Dict, Any, Optional, Callable
import config
from core.llm_engine import LLMEngine
from core.tts_engine import TTSEngine
from core.image_engine import ImageEngine
from core.video_engine import VideoEngine
from core.publisher import MetaPublisher


class ReelPipeline:
    def __init__(
        self,
        voice: str = config.DEFAULT_VOICE,
        gemini_key: Optional[str] = None,
        groq_key: Optional[str] = None
    ):
        self.voice = voice
        self.llm = LLMEngine(gemini_api_key=gemini_key, groq_api_key=groq_key)
        self.tts = TTSEngine(default_voice=voice)
        self.image_gen = ImageEngine(width=config.VIDEO_WIDTH, height=config.VIDEO_HEIGHT)
        self.video_gen = VideoEngine(width=config.VIDEO_WIDTH, height=config.VIDEO_HEIGHT, fps=config.FPS)
        self.publisher = MetaPublisher()

    def generate_full_reel(
        self,
        prompt: str,
        niche: str = "General",
        voice: Optional[str] = None,
        bg_music_path: Optional[Path] = None,
        auto_publish: bool = False,
        progress_callback: Optional[Callable[[str, float], None]] = None
    ) -> Dict[str, Any]:
        """
        Executes the full automated reel creation lifecycle from a single prompt.
        """
        start_time = time.time()
        job_id = f"reel_{int(start_time)}"
        job_dir = config.OUTPUT_DIR / job_id
        job_dir.mkdir(parents=True, exist_ok=True)

        selected_voice = voice or self.voice

        def notify(msg: str, pct: float):
            print(f"[{int(pct*100)}%] {msg}")
            if progress_callback:
                progress_callback(msg, pct)

        # 1. Script Generation
        notify("Generating viral script and scene visual prompts...", 0.1)
        script_data = self.llm.generate_script(prompt, niche)
        title = script_data.get("title", "Daily Discovery")
        scenes = script_data.get("scenes", [])
        caption = script_data.get("caption", "")
        hashtags = script_data.get("hashtags", [])

        if not scenes:
            raise ValueError("No scenes generated by LLM engine.")

        processed_scenes = []

        # 2. Audio & Visuals per Scene
        total_scenes = len(scenes)
        for i, scene in enumerate(scenes):
            scene_num = i + 1
            narration = scene.get("narration", "")
            vis_prompt = scene.get("visual_prompt", "")

            notify(f"Generating scene {scene_num}/{total_scenes}: Neural voiceover...", 0.2 + (0.2 * (i / total_scenes)))
            audio_file = job_dir / f"scene_{scene_num}_audio.mp3"
            self.tts.generate_voiceover(narration, audio_file, voice=selected_voice)

            notify(f"Generating scene {scene_num}/{total_scenes}: 9:16 AI Visual...", 0.3 + (0.2 * (i / total_scenes)))
            img_file = job_dir / f"scene_{scene_num}_image.jpg"
            self.image_gen.generate_image(vis_prompt, img_file)

            processed_scenes.append({
                "scene_id": scene_num,
                "narration": narration,
                "image_path": img_file,
                "audio_path": audio_file
            })

        # 3. Video Assembly & Motion Animation
        notify("Rendering animated 9:16 video with dynamic captions...", 0.7)
        final_video_path = job_dir / f"{job_id}_final.mp4"
        self.video_gen.assemble_reel(
            scenes_data=processed_scenes,
            output_path=final_video_path,
            bg_music_path=bg_music_path
        )

        # 4. Save to Queue / Auto-Publish
        notify("Saving reel to library and publishing queue...", 0.9)
        full_caption = f"{caption}\n\n{' '.join(hashtags)}"
        self.publisher.save_to_publish_queue(
            video_path=final_video_path,
            title=title,
            caption=full_caption,
            hashtags=hashtags
        )

        publish_result = None
        if auto_publish:
            notify("Triggering Meta Auto-Publishing...", 0.95)
            if self.publisher.is_configured()["facebook"]:
                publish_result = self.publisher.publish_facebook_reel(final_video_path, full_caption)

        notify("Reel generated successfully!", 1.0)

        elapsed = time.time() - start_time
        return {
            "job_id": job_id,
            "title": title,
            "video_path": str(final_video_path),
            "script_data": script_data,
            "caption": full_caption,
            "hashtags": hashtags,
            "elapsed_seconds": round(elapsed, 1),
            "published": publish_result
        }
